owner: badges
repo: uptime-monitoring

sites:
  - name: Shields.io homepage
    url: https://shields.io/
  - name: Static Badge
    url: https://img.shields.io/badge/foo-bar-blue
  - name: NPM version badge
    url: https://img.shields.io/npm/v/badge-maker
  - name: GitHub issues badge
    url: https://img.shields.io/github/issues-search?query=repo%3Abadges%2Fshields

status-website:
  baseUrl: /uptime-monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Shields.io Status
  introTitle: Shields.io Uptime Monitoring
  introMessage: Pings for various endpoints on [shields.io](https://shields.io/), pwered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status Page
      href: /
    - title: Status Repo
      href: https://github.com/$OWNER/$REPO
    - title: Shields.io
      href: https://shields.io/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
